name: CI

on:
  push:
    branches:
      - develop
      - main
      - master
      - workos
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: write

jobs:
  lint-php:
    name: PHP Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: true  # nodig voor de auto-commit

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: '8.4'

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run Pint
        run: composer lint

      - name: Commit PHP fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'fix: code style (pint)'
          commit_options: '--no-verify'

  lint-frontend:
    name: Frontend Linting & Typechecking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: true  # nodig voor de auto-commit

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: '8.4'

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate Wayfinder Types
        run: php artisan wayfinder:generate --no-interaction

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install NPM Dependencies
        run: npm ci

      - name: Format Frontend
        run: npm run format

      - name: Lint Frontend
        run: npm run lint

      - name: Typecheck Frontend
        run: npm run types:check

      - name: Commit frontend fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'fix: code style (prettier + wayfinder)'
          commit_options: '--no-verify'